# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path: 
work_dir: ./workdir
no_progress_bar: False

# Visualization
visualization_class: 0
visualization_sample: 0
visualization_frames: []

# Data Loader
# ntu-xsub, ntu-xview, ntu-xsub120, ntu-xset120
dataset: zensho
dataset_args:
  ntu:
    train_batch_size: 32
    eval_batch_size: 32
    num_frame: 288
    inputs: JVB
    transform: False
    root_folder: /data/yifan.song/dataset/NTU_skeleton/npy_dataset
    ntu60_path: /data/yifan.song/dataset/NTU_skeleton/nturgbd_skeletons_s001_to_s017
    ntu120_path: /data/yifan.song/dataset/NTU_skeleton/nturgbd_skeletons_s018_to_s032
  gw:
    train_batch_size: 16
    eval_batch_size: 16
    preprocess: False
    num_frame: 300
    inputs: JVB
    transform: False
    root_folder: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_procrocessed
    gw_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_skeletons
  zensho:
    train_batch_size: 1
    eval_batch_size: 1
    preprocess: False
    num_frame: 1000
    inputs: JVB
    transform: False
    root_folder: /home/mtk/Downloads/action_dataset/Skeletons/preprocessed
    zensho_data_path: /home/mtk/Downloads/action_dataset/Skeletons/Skeletons
  rtar:
    train_batch_size: 8
    eval_batch_size: 8
    preprocess: False
    num_frame: 110
    inputs: JVB
    transform: False
    root_folder: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/newer_preprocessed
    rtar_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/skeletons

# Model
model_type: EfficientGCN-B4
model_args:
  stem_channel: 64
  block_args: [[48,1,0.5],[24,1,0.5],[64,2,1],[128,2,1]]
  fusion_stage: 2
  act_type: swish
  att_type: stja
  layer_type: Sep
  drop_prob: 0.25
  kernel_size: [5,2]
  scale_args: [1.2,1.35]
  expand_ratio: 2
  reduct_ratio: 4
  bias: True
  edge: True

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 100
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 70
    warm_up: 10
