config: '2001'
dataset: zensho
dataset_args:
  gw:
    eval_batch_size: 16
    gw_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_skeletons
    inputs: JVB
    num_frame: 300
    preprocess: false
    root_folder: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_procrocessed
    train_batch_size: 16
    transform: false
  ntu:
    eval_batch_size: 32
    inputs: JVB
    ntu120_path: /data/yifan.song/dataset/NTU_skeleton/nturgbd_skeletons_s018_to_s032
    ntu60_path: /data/yifan.song/dataset/NTU_skeleton/nturgbd_skeletons_s001_to_s017
    num_frame: 288
    root_folder: /data/yifan.song/dataset/NTU_skeleton/npy_dataset
    train_batch_size: 32
    transform: false
  rtar:
    eval_batch_size: 8
    inputs: JVB
    num_frame: 110
    preprocess: false
    root_folder: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/newer_preprocessed
    rtar_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/skeletons
    train_batch_size: 8
    transform: false
  zensho:
    eval_batch_size: 1
    inputs: JVB
    num_frame: 1000
    preprocess: false
    root_folder: /home/mtk/Downloads/action_dataset/Skeletons/preprocessed
    train_batch_size: 1
    transform: false
    zensho_data_path: /home/mtk/Downloads/action_dataset/Skeletons/Skeletons
debug: false
delay_hours: 0
evaluate: false
extract: false
generate_data: false
gpus:
- 0
lr_scheduler: cosine
model_args:
  act_type: swish
  att_type: stja
  bias: true
  block_args:
  - - 48
    - 1
    - 0.5
  - - 24
    - 1
    - 0.5
  - - 64
    - 2
    - 1
  - - 128
    - 2
    - 1
  drop_prob: 0.25
  edge: true
  expand_ratio: 2
  fusion_stage: 2
  kernel_size:
  - 5
  - 2
  layer_type: Sep
  reduct_ratio: 4
  scale_args:
  - 1.2
  - 1.35
  stem_channel: 64
model_type: EfficientGCN-B4
no_progress_bar: false
optimizer: SGD
optimizer_args:
  Adam:
    betas:
    - 0.9
    - 0.99
    lr: 0.1
    weight_decay: 0.0001
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0001
pretrained_path: null
resume: false
scheduler_args:
  cosine:
    max_epoch: 70
    warm_up: 10
  step:
    max_epoch: 100
    step_lr:
    - 20
    - 50
    warm_up: 10
seed: 1
visualization_class: 0
visualization_frames: []
visualization_sample: 0
visualize: false
work_dir: ./workdir
