config: '1001'
dataset: zensho
dataset_args:
  gw:
    eval_batch_size: 16
    gw_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_skeletons
    path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_procrocessed
    preprocess: false
    train_batch_size: 16
  gw-3d:
    eval_batch_size: 16
    gw_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_skeletons
    gw_depth_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_depth
    path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/gw-action/newer_procrocessed
    preprocess: false
    train_batch_size: 16
  ntu:
    eval_batch_size: 8
    ntu120_data_path: /data1/yifan.song/NTU_RGBD/nturgbd_skeletons_s018_to_s032
    ntu60_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/NTU_dataset/nturgb+d_skeletons
    path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/NTU_dataset/preprocessed
    preprocess: false
    train_batch_size: 8
  rtar:
    eval_batch_size: 16
    gw_data_path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/skeletons
    path: /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/datasets/realtime_action_recognition/preprocessed
    preprocess: false
    train_batch_size: 16
  zensho:
    eval_batch_size: 4
    path: /home/mtk/Downloads/action_dataset/Skeletons/preprocessed
    preprocess: false
    train_batch_size: 4
    zensho_data_path: /home/mtk/Downloads/action_dataset/Skeletons/Skeletons
debug: false
evaluate: false
extract: false
generate_data: false
generate_label: false
gpus:
- 0
lr_scheduler: cosine
model_args:
  kernel_size:
  - 9
  - 2
model_type: pa-resgcn-b29
no_progress_bar: false
optimizer: SGD
optimizer_args:
  Adam:
    betas:
    - 0.9
    - 0.99
    lr: 0.1
    weight_decay: 0.0002
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0002
path: ''
pretrained_path: ./pretrained
resume: false
scheduler_args:
  cosine:
    max_epoch: 100
    warm_up: 5
  step:
    max_epoch: 100
    step_lr:
    - 20
    - 50
    warm_up: 10
seed: 1
visualization: false
visualization_class: 0
visualization_frames: []
visualization_sample: 0
work_dir: ./workdir
