config: '1001'
dataset: ntu-xsub
dataset_args:
  ntu:
    eval_batch_size: 64
    ntu120_data_path: /data1/yifan.song/NTU_RGBD/nturgbd_skeletons_s018_to_s032
    ntu60_data_path: /data1/yifan.song/NTU_RGBD/nturgbd_skeletons_s001_to_s017
    path: /data1/yifan.song/SkeletonPreprocess
    preprocess: false
    train_batch_size: 32
debug: false
evaluate: false
extract: false
generate_data: false
generate_label: false
gpus:
- 0
- 1
lr_scheduler: cosine
model_args:
  kernel_size:
  - 9
  - 2
model_type: resgcn-n51-r4
no_progress_bar: false
optimizer: SGD
optimizer_args:
  Adam:
    betas:
    - 0.9
    - 0.99
    lr: 0.1
    weight_decay: 0.0002
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0002
path: ''
pretrained_path: ./pretrained
resume: false
scheduler_args:
  cosine:
    max_epoch: 50
    warm_up: 5
  step:
    max_epoch: 70
    step_lr:
    - 20
    - 50
    warm_up: 10
seed: 1
visualization: false
visualization_class: 0
visualization_frames: []
visualization_sample: 0
work_dir: ./workdir
