gpus: [0]
seed: 1
debug: False
pretrained_path: './pretrained'
work_dir: './workdir'
no_progress_bar: False

# Visualization
visualization_class: 0
visualization_sample: 0
visualization_frames: []

# Data Loader
# ntu-xsub, ntu-xview, ntu-xsub120, ntu-xset120
dataset: zensho
dataset_args:
  zensho:
    train_batch_size: 4
    eval_batch_size: 4
    preprocess: False
    path: /home/mtk/Downloads/action_dataset/Skeletons/preprocessed
    zensho_data_path: /home/mtk/Downloads/action_dataset/Skeletons/Skeletons
# Model
# pa, ca, fa, sa, pca, psa
# b15, b19, b23, b29, n39, n51, n57, n75
# r1, r2, r4, r8
#model_type: resgcn-n51-r4
model_type: pa-resgcn-b29
model_args:
  kernel_size: [9,2]

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0002
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0002

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 100
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 100
    warm_up: 5
