# Pose Estimation
POSE:
  AUTO_RESUME: true
  CUDNN:
    BENCHMARK: true
    DETERMINISTIC: false
    ENABLED: true
  DATA_DIR: ''
  GPUS: (0)
  OUTPUT_DIR: 'output'
  LOG_DIR: 'log'
  WORKERS: 12
  PRINT_FREQ: 100

  DATASET:
    COLOR_RGB: true
    DATASET: 'coco'
    DATA_FORMAT: png
    FLIP: true
    NUM_JOINTS_HALF_BODY: 8
    PROB_HALF_BODY: 0.3
    ROOT: '../dataset/zensho_coco_aug'
    ROT_FACTOR: 45
    SCALE_FACTOR: 0.35
    TEST_SET: 'val'
    TRAIN_SET: 'train'
  MODEL:
    INIT_WEIGHTS: true
    NAME: pose_hrnet
    NUM_JOINTS: 17
    PRETRAINED: 'dark/models/pytorch/imagenet/hrnet_w48-8ef0771d.pth'
    TARGET_TYPE: gaussian
    IMAGE_SIZE:
    - 288
    - 384
    HEATMAP_SIZE:
    - 72
    - 96
    SIGMA: 3
    EXTRA:
      PRETRAINED_LAYERS:
      - 'conv1'
      - 'bn1'
      - 'conv2'
      - 'bn2'
      - 'layer1'
      - 'transition1'
      - 'stage2'
      - 'transition2'
      - 'stage3'
      - 'transition3'
      - 'stage4'
      FINAL_CONV_KERNEL: 1
      STAGE2:
        NUM_MODULES: 1
        NUM_BRANCHES: 2
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        NUM_CHANNELS:
        - 48
        - 96
        FUSE_METHOD: SUM
      STAGE3:
        NUM_MODULES: 4
        NUM_BRANCHES: 3
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        - 4
        NUM_CHANNELS:
        - 48
        - 96
        - 192
        FUSE_METHOD: SUM
      STAGE4:
        NUM_MODULES: 3
        NUM_BRANCHES: 4
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
        NUM_CHANNELS:
        - 48
        - 96
        - 192
        - 384
        FUSE_METHOD: SUM
  LOSS:
    USE_TARGET_WEIGHT: true
  TRAIN:
    BATCH_SIZE_PER_GPU: 4
    SHUFFLE: true
    BEGIN_EPOCH: 0
    END_EPOCH: 30
    OPTIMIZER: adam
    LR: 0.001
    LR_FACTOR: 0.1
    LR_STEP:
    - 170
    - 200
    WD: 0.0001
    GAMMA1: 0.99
    GAMMA2: 0.0
    MOMENTUM: 0.9
    NESTEROV: false
  TEST:
    BATCH_SIZE_PER_GPU: 4
    COCO_BBOX_FILE: '../dataset/zensho_coco_aug/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
    BBOX_THRE: 1.0
    IMAGE_THRE: 0.0
    IN_VIS_THRE: 0.1
    MODEL_FILE: '../models/dark/pose_hrnet_w48_384x288.pth'
    NMS_THRE: 1.0
    OKS_THRE: 0.9
    USE_GT_BBOX: true
    FLIP_TEST: true
    POST_PROCESS: true
    SHIFT_HEATMAP: true
  DEBUG:
    DEBUG: true
    SAVE_BATCH_IMAGES_GT: true
    SAVE_BATCH_IMAGES_PRED: true
    SAVE_HEATMAPS_GT: true
    SAVE_HEATMAPS_PRED: true

# Action Recognition
# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path: './pretrained'
work_dir: './workdir'
no_progress_bar: False

# Visualization
visualization_class: 0
visualization_sample: 0
visualization_frames: []

# Data Loader
# ntu-xsub, ntu-xview, ntu-xsub120, ntu-xset120
dataset: zensho
dataset_args:
  zensho:
    train_batch_size: 4
    eval_batch_size: 4
    preprocess: False
    path: /home/mtk/Downloads/action_dataset/Skeletons/preprocessed
    zensho_data_path: /home/mtk/Downloads/action_dataset/Skeletons/Skeletons
# Model
# pa, ca, fa, sa, pca, psa
# b15, b19, b23, b29, n39, n51, n57, n75
# r1, r2, r4, r8
#model_type: resgcn-n51-r4
model_type: pa-resgcn-b29
model_args:
  kernel_size: [9,2]

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0002
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0002

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 100
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 100
    warm_up: 5

# inference
# action_model : /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/action_recognition/ResGCNv1/workdir/1001_pa-resgcn-b29_gw/2021-07-14 00-55-27_60frames/1001_pa-resgcn-b29_gw.pth.tar
# video_input : /media/mtk/559be1a1-ed84-4771-ac8e-97e50374afcd/Workspace/action_recognition/ResGCNv1/test/boxing.mkv
# drop : 10